version: "3.7"
services:
  streamlit:
    build: ./docker/streamlit
    container_name: streamlit
    command: "streamlit run dashboard.py"
    ports:
      - "8501:8501"
    volumes:
      - "./src/app:/usr/src/app"

  notebook:
    build: ./docker/notebook
    container_name: notebook
    ports:
      - "8888:8888"
    volumes:
      - "./src/notebook:/home/jovyan/work"